### ISSUE TITLE
Can't import module

### ISSUE THREAD

**Issue by JeroenDelcour** [windfish-studio/three-map-controls#14]
Installing the module from npm and importing it gives the following error:

```javascript
vm.js:94 Uncaught /node_modules/@windfish-studio/three-map-controls/src/three-map-controls.js:5
import {
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:86:7)
    at createScript (vm.js:268:10)
    at Object.runInThisContext (vm.js:316:10)
    at Module._compile (internal/modules/cjs/loader.js:805:26)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
```

Am I doing something wrong? I tried downgrading to 1.0.1 but it gave the same error.

**Comment by sikanrong** [comment]
In general the module is written in such a way that it rather depends on being used in a webpack project, in the sense that it only includes the ES6+ source, and doesn't include logic to precompile into CJS format for direct use (in a nodejs/electron project). 

I can fix it so that this would happen automatically, but perhaps in the meantime this helps - all you need to do is configure your electron project in such a way that it uses babel to precompile this down to regular javascript (cjs)

**Comment by JeroenDelcour** [comment]
Ah, I see. I'm still a little new to the whole JavaScript ecosystem, thanks for explaining. I'll look into that.
